---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: trivy
  namespace: security-scan
spec:
  chart:
    spec:
      chart: trivy-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aqua
      version: 0.18.4
  interval: 1m0s
