name: Setup cluster

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  workflow_dispatch:

jobs:
  setup-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Start minikube
      id: minikube
      uses: medyagh/setup-minikube@latest
    - name: kubectl
      run: kubectl get pods -A -o wide
    - name: Setup cluster
      run: |
        ./run.sh
    - name: kubectl
      run: |
        kubectl get pods -A -o wide && \
        kubectl get helmrelease -A
