name: Scan
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Scan images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/bbusse/gtfso-import'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/bbusse/gtfso-vbb'
          format: 'sarif'
          output: 'trivy-results.sarif'
